name: continuous-integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-build-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo build --all --all-targets --all-features

  lint:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-lint-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all --all-targets --all-features -- -D warnings
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - run: cargo machete

  fmt:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-fmt-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli@0.9.3
      - name: Run taplo format
        run: taplo format
      - name: Check for a diff
        run: git diff --exit-code

  cargo-deny-checks:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-cargo-deny-checks-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny
      - name: cargo deny
        run: cargo deny -L error --workspace check bans advisories sources

  readme-up-to-date:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-readme-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cargo run -- --username killzoner --template template.hbs > README.md.new
      - name: Check README is up to date
        run: diff -u README.md README.md.new
